### ISSUE TITLE
TalentRequest object is not being created when nested with finalRequest

### ISSUE THREAD

**Issue by ifebrand6** [Innarticles/hive#9]
I am using Active Record Nested Attributes, to nest the FinalizedRequest and TalentAssignment. so when the admin assigns an expert; a finalized_request is being created.
However the Finalized request is being created, the TalentAssignment is not.
**This are the models:**

> class FinalizedRequest < ApplicationRecord
>   belongs_to :user
>   belongs_to :request
>   has_many  :talent_assignments, inverse_of: :finalized_request
>   accepts_nested_attributes_for :talent_assignments, reject_if: :reject_talent_assignment,  allow_destroy: true
>   _ #validates_presence_of :talent_assignments_
> 
>   def reject_talent_assignment
>     attributes['finalized_request_id'].blank?
>   end
>   
> end

> class TalentAssignment < ApplicationRecord
>   validates :finalized_request, presence: true
>   belongs_to :finalized_request,inverse_of: :talent_assignments
>   belongs_to :expert_application
> 
> end

**The controller actions**

> def talent_assignment
>     @talent_request = TalentRequest.find(params[:id]) #use to get the TalentRequest and populated to fill in the final request params
>     @talents = ExpertApplication.all.where(talent_type: @talent_request.talent_type_id)
>     @final_request = FinalizedRequest.new
>     @final_request.talent_assignments.build
>   end
>   def finalize_user_request
>       @final_request = FinalizedRequest.new(final_params)
>       if @final_request.save
>       flash[:notice] = "Talent Assign successfully"
>       redirect_to root_path
>     else
>       render :talent_assignment
>     end
>   end
**the params** 

>  def final_params
>       params.require(:finalized_request).permit(:user_id, :request_id, talent_assignments_attributes: [:id,:engaged_date, :start_date,:expert_application_id, :finalized_request, :_destroy])
>     end
**finally the form**
 

> <%= form_for @final_request ,  url: {action: "finalize_user_request"} do |f| %>
>         <%= f.hidden_field :user_id, value: @talent_request.user_id %>
>         <%= f.hidden_field :request_id, value: @talent_request.request_id %>
> 
>     <%= f.fields_for :talent_assignments do |a| %>
>         <%= a.label :engaged_date, "Engaged_date" %>
>         <%= a.date_field :engaged_date %>
>         <br>
>         <%= a.label :engaged_date, "Start Date" %>
>         <%= a.date_field  :start_date %>
>         <br>
>         <%= a.label :engaged_date, "Select Expert" %>
>         <%= a.select(:expert_application_id, @talents.collect{|e| [e.firstName   , + e.id]} ) %>
>         <%= a.check_box :_destroy %>
>         <%= a.label :_destroy, "remove" %>
>         <br>
> 
> <% end %>
> <%= f.submit %>
> <% end %>

**Comment by Innarticles** [comment]
Looking into this

**Comment by ifebrand6** [comment]
I have successfully fixed this issue, apparently, in the Finalized Request model, a validation is set that prevents a talent from being assigned.
